### ISSUE TITLE
Installation issue via Cocoapods

### ISSUE THREAD

**Issue by sunnyyoung** [mmoaay/MBNetwork#27]
### Check List

- [x] I have read the [README.md](https://github.com/mmoaay/Bamboots/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/mmoaay/Bamboots/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

Install `Bamboots` via Cocoapods without specify a git url will fail in building.

#### Reproduce

1. Install `Bamboots` with the podfile config below:

```
target 'ProjectName' do
  use_frameworks!
  pod 'Bamboots'
end
```

And the result will be:

```
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.5.1)
Using AlamofireObjectMapper (4.1.0)
Using Bamboots (0.5.0)
Using ObjectMapper (2.2.9)
Using Realm (3.0.2)
Using RealmSwift (3.0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.
```

![image](https://user-images.githubusercontent.com/5926284/33377606-0d81630c-d54d-11e7-9a98-fc064ea93951.png)

2. Install `Bamboots` with the podfile config below:

```
platform :ios, '10.0'
target 'ProjectName' do
  use_frameworks!
  pod 'Bamboots', :git => 'git@github.com:mmoaay/Bamboots.git'
end
```

And the result will be:

```
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.5.1)
Using AlamofireCodable (0.1.1)
Using Bamboots (0.5.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

Everything is ok.

#### Other Comment

Found this: https://github.com/CocoaPods/Specs/blob/master/Specs/2/3/e/Bamboots/0.5.0/Bamboots.podspec.json

**Comment by mmoaay** [comment]
Sorry, we have something wrong with our puslish, We've already release a new version 0.6.0 to fix this problem.

You can find it at:
https://github.com/CocoaPods/Specs/blob/master/Specs/2/3/e/Bamboots/0.6.0/Bamboots.podspec.json

Thank you for your issue
