### ISSUE TITLE
uibutton  action 

### ISSUE THREAD

**Issue by Alfulayt** [mmoaay/MBNetwork#8]
thank you for this awesome library 
but there is a problem in UIButtons
because you used an extension for UIbutton we can't add actions from storyboards in any views

**Comment by mmoaay** [comment]
Thank you for issue，I've got the same problem when writing the demo, and I found it was the bug of Xcode...So do you have any suggestions?

**Comment by mmoaay** [comment]
I've fixed this bug by extending UIControl instead of UIButton. And it will be available in Version 0.4.0
